### ISSUE TITLE
Solution: Repos component's useEffect() isn't set up with the right prop name.

### ISSUE THREAD

**Issue by rooberrydev** [sofiapoh/react-dynamic-data-workshop#10]
the Card component passes in a property 'url' to the repos component
```
{repos_url ? <Repos url={repos_url} /> : null}
```
but it is referred to in useEffect() , in the Repos component as props.repos (line 11).
This should be props.url
```
  React.useEffect(() => {
    getData(props.url).then(repos => setRepos(repos));
  }, [props.repos]);
```

**Comment by sofiapoh** [comment]
Would you like to open a PR to fix this?

**Comment by rooberrydev** [comment]
@sofiapoh I have opened a PR, sorry for the delay. it's a really minor change, but this part of the solution was used to explain hook dependencies to fac17, and I found it confusing that the dependency "props.repos" was neither passed in to the component, nor used within the useEffect() hook.
I asked @oliverjam and he said it should be props.url.

**Comment by oliverjam** [comment]
Thanks! Yeah I fixed this locally as I was going through the solution but forgot to commit it 🤦‍♂
