### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by oliverjam** [sofiapoh/react-dynamic-data-workshop#27]
Is it worth switching over from Parcel? They're both basically zero-config so there's not really anything students will learn from the build setup.

**Comment by sofiapoh** [comment]
I think maybe but also what we have right now _does_ work so I didn't want to go through the trouble of setting up CRA and then deleting a bunch of the crud that it adds which is not needed for the workshop. If you have some spare time it may not be a bad idea!
