### ISSUE TITLE
GitHub tokens

### ISSUE THREAD

**Issue by oliverjam** [sofiapoh/react-dynamic-data-workshop#28]
Do we definitely need tokens? I guess if a whole bunch of people do the workshop on the same network we may have rate-limiting issues?I remember lots of people having issues with exporting/using the token for some reason, so would be nice if we could skip that step.

Alternatively if we did use CRA it [automatically loads env vars from a `.env`](https://create-react-app.dev/docs/adding-custom-environment-variables/), so we could use that instead of a custom JS export.

Finally I noticed they're [deprecating tokens in query params](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/), so maybe we should switch to using an `authorization` header? This is what they'll have used in Weeks 7/8 of the new curriculum anyway.

**Comment by sofiapoh** [comment]
Yeah I was thinking about this, the simplest step would probably be skipping tokens entirely as they're most likely not going to be needed but make a note about `authorization` header in case someone might run into trouble?

**Comment by oliverjam** [comment]
Yeah that would be simplest. It only takes one runaway `useEffect` to get rate-limited though 😅
