### ISSUE TITLE
Typo in the code

### ISSUE THREAD

**Issue by sbinlondon** [sofiapoh/react-dynamic-data-workshop#4]
Line #245 in the readme:

<ul>{this.state.repos.map(repo => <Repo key={repo.id} {...repo />})}</ul>

Should be:

<ul>{this.state.repos.map(repo => <Repo key={repo.id} {...repo }/>)}</ul>

The closing tag for Repo key was inside the closing curly brace for ...repo

**Comment by sofiapoh** [comment]
Thanks! Do you want to open a PR to fix this?

**Comment by sofiapoh** [comment]
Fixed
