### ISSUE TITLE
Access token name mismatch

### ISSUE THREAD

**Issue by oliverjam** [sofiapoh/react-dynamic-data-workshop#6]
A few people yesterday got caught out by following along too closely with the readme. You `export const token` but then `import { accessToken }` later. One person suggested it's good to have stuff like that to keep them on their toes, but it might be worth making them match.

Sidenote: almost half the class tried to default import the token and were confused that it was `undefined`. Not sure we can fix that but something to note

**Comment by sofiapoh** [comment]
Alright, I'll add a note about that. Good catch. Do they get explained named/default imports before this?

**Comment by oliverjam** [comment]
Yeah it was covered in the morning challenge on Monday, along with ES6 classes. I think the problem was just blindly copying the readme really, so it's not the worst thing for it to error and force them to think to fix it
