### ISSUE TITLE
Link to componentDidMount recap

### ISSUE THREAD

**Issue by oliverjam** [sofiapoh/react-dynamic-data-workshop#7]
Lots of people were confused when they first encountered cDM (some pairs put it inside render, some inside the state object etc). I think they probably skimmed over that part of Monday's React API workshop. I ended up sending a link to the [Lifecycle Methods](https://github.com/oliverjam/intro-react-workshop/tree/master/03-surpass-with-class#lifecycle-methods) section in Gitter so people could refresh their memories.

Is it worth adding a note to that section like: "It might be worth re-reading this section [link] from yesterday if you're struggling"?

**Comment by sofiapoh** [comment]
Looks like it might be a good idea to add links to relevant react docs to all sections that mention a concept explained there!

**Comment by oliverjam** [comment]
Probably not needed since the hooks rewrite
