### ISSUE TITLE
Introducing passing props

### ISSUE THREAD

**Issue by oliverjam** [sofiapoh/react-dynamic-data-workshop#8]
Although it gets talked about in the abstract on Monday they've never actually encountered passing down props on their own at this point. When people got to the second part of this workshop (making `<RepoList />` almost nobody really knew how to pass a prop down to it, or even thought of doing so).

I'm not sure if there's a better way to introduce the basic concept of doing `<Component prop={value} />`. Maybe that belongs on Monday—the only practice they get is the [Stopwatch workshop](https://github.com/oliverjam/intro-react-workshop/blob/master/workshop-top-notch-stopwatch/README.md), which is a single class, with no props to pass.

**Comment by sofiapoh** [comment]
I can definitely add more explanation around this! Somehow I thought this was covered by learning React API

**Comment by oliverjam** [comment]
Well I think maybe it should be. We definitely showed it, but they never got to try it themselves, so it probably slipped straight out of their heads.

I'm not sure if it should go in the Stopwatch workshop or here :/

**Comment by oliverjam** [comment]
Okay I've written a [totally new intro workshop](https://github.com/oliverjam/react-food-workshop) for Monday afternoon that should cover passing props so we can close this :)
